import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:photo_manager/photo_manager.dart';
import 'package:vendor_app/models/product.dart';
import 'package:vendor_app/models/order.dart' as order_model;
import 'package:vendor_app/services/product_service.dart';
import 'package:vendor_app/services/business_inventory_service.dart';
import 'package:vendor_app/services/store_inventory_service.dart';
import 'package:vendor_app/services/media_service.dart';
import 'dart:typed_data';

/// Service for handling direct sell-from-media functionality
/// This bypasses the manual inventory allocation flow while maintaining data consistency
class DirectSellService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final ProductService _productService;
  final BusinessInventoryService _businessInventoryService;
  final StoreInventoryService _storeInventoryService;
  final MediaService _mediaService;

  DirectSellService({
    required ProductService productService,
    required BusinessInventoryService businessInventoryService,
    required StoreInventoryService storeInventoryService,
    required MediaService mediaService,
  })  : _productService = productService,
        _businessInventoryService = businessInventoryService,
        _storeInventoryService = storeInventoryService,
        _mediaService = mediaService;

  /// Complete flow: Create product, add to inventory, and create sale order
  Future<DirectSellResult> sellMediaDirectly({
    required AssetEntity media,
    required String businessId,
    required String businessName,
    required String vendorId,
    required String storeId,
    required String storeName,
    required DirectSellRequest request,
  }) async {
    try {
      // Step 1: Create product from media
      final product = await _createProductFromMedia(
        media: media,
        businessId: businessId,
        vendorId: vendorId,
        request: request,
      );

      // Step 2: Add to business inventory (warehouse level)
      final businessInventoryId = await _addToBusinessInventory(
        productId: product.id,
        businessId: businessId,
        request: request,
      );

      // Step 3: Allocate to store inventory
      await _allocateToStoreInventory(
        businessId: businessId,
        businessName: businessName,
        vendorId: vendorId,
        storeId: storeId,
        businessInventoryId: businessInventoryId,
        productId: product.id,
        request: request,
      );

      // Step 4: Create and process the sale order
      final order = await _createSaleOrder(
        productId: product.id,
        vendorId: vendorId,
        request: request,
      );

      return DirectSellResult(
        success: true,
        productId: product.id,
        productName: product.name,
        orderId: order.id,
        businessInventoryId: businessInventoryId,
        totalAmount: order.total,
      );

    } catch (error) {
      return DirectSellResult(
        success: false,
        errorMessage: error.toString(),
      );
    }
  }

  /// Create product from media asset
  Future<Product> _createProductFromMedia({
    required AssetEntity media,
    required String businessId,
    required String vendorId,
    required DirectSellRequest request,
  }) async {
    // Get media as bytes for upload
    final Uint8List? mediaBytes = await media.originBytes;
    if (mediaBytes == null) {
      throw Exception('Failed to process media file');
    }

    // First create product to get productId for organized storage
    final tempProduct = Product(
      id: '', // Will be generated by Firestore
      name: request.productName,
      description: request.productDescription ?? 'Product created from media',
      price: request.sellingPrice,
      images: [], // Will be populated after upload
      stock: request.quantity, // Set initial stock
      minQuantity: request.minimumQuantity ?? 1, // Default minimum quantity
      rating: 0.0,
      reviews: 0,
      category: request.category ?? 'Uncategorized',
      tags: request.tags ?? [],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      vendorId: vendorId,
      businessId: businessId,
      unit: request.unit,
    );

    // Create product using ProductService to get the productId
    final productId = await _productService.createProduct(
      tempProduct,
      businessId: businessId,
      initialQuantity: request.quantity,
      costPrice: request.costPrice,
      sellingPrice: request.sellingPrice,
    );

    if (productId == null) {
      throw Exception('Failed to create product');
    }

    try {
      // Upload media to Firebase Storage with productId for organization
      // Use optimized compression settings for product images
      final fileName = '${media.type.name}_${DateTime.now().millisecondsSinceEpoch}.${_getFileExtension(media.type)}';
      // Get compression settings for product image
      final compressionSettings = _getCompressionSettings('product_image');
      
      final downloadUrl = await _mediaService.uploadMediaFromBytesWithCompression(
        bytes: mediaBytes,
        fileName: fileName,
        type: media.type == AssetType.video ? 'video' : 'image',
        vendorId: vendorId,
        productId: productId,
        maxSizeBytes: compressionSettings['maxSizeBytes'],
        maxWidth: compressionSettings['maxWidth'],
        maxHeight: compressionSettings['maxHeight'],
        quality: compressionSettings['quality'],
        forceCompression: compressionSettings['forceCompression'],
      );

      if (downloadUrl == null) {
        throw Exception('Failed to upload media to storage');
      }

      // Update product with the uploaded image URL
      final updatedProduct = tempProduct.copyWith(
        id: productId,
        images: [downloadUrl], // Add the uploaded image URL
      );

      // Update the product in Firestore with the image URL
      await _productService.updateProduct(updatedProduct);

      return updatedProduct;
    } catch (uploadError) {
      // If upload fails, we should still return the product but log the error
      print('Warning: Failed to upload media for product $productId: $uploadError');
      
      // Return product without images - it's still functional
      return tempProduct.copyWith(id: productId);
    }
  }

  /// Helper method to get appropriate file extension based on asset type
  String _getFileExtension(AssetType type) {
    switch (type) {
      case AssetType.image:
        return 'jpg';
      case AssetType.video:
        return 'mp4';
      default:
        return 'jpg';
    }
  }

  /// Get optimized compression settings for different use cases
  Map<String, dynamic> _getCompressionSettings(String useCase) {
    switch (useCase.toLowerCase()) {
      case 'product_image':
        return {
          'maxSizeBytes': 1024 * 1024, // 1MB - good balance for product display
          'maxWidth': 1920,
          'maxHeight': 1080,
          'quality': 85, // High quality for product images
        };
      case 'thumbnail':
        return {
          'maxSizeBytes': 200 * 1024, // 200KB for thumbnails
          'maxWidth': 600,
          'maxHeight': 600,
          'quality': 75,
        };
      case 'gallery':
        return {
          'maxSizeBytes': 2 * 1024 * 1024, // 2MB for gallery images
          'maxWidth': 2048,
          'maxHeight': 2048,
          'quality': 90, // Higher quality for gallery
        };
      default:
        return {
          'maxSizeBytes': 1024 * 1024, // 1MB default
          'maxWidth': 1920,
          'maxHeight': 1080,
          'quality': 85,
        };
    }
  }

  /// Add product to business inventory (warehouse level)
  Future<String> _addToBusinessInventory({
    required String productId,
    required String businessId,
    required DirectSellRequest request,
  }) async {
    final businessInventoryId = await _businessInventoryService.createBusinessInventory(
      businessId: businessId,
      productId: productId,
      productName: request.productName,
      category: request.category ?? 'Uncategorized',
      totalQuantity: request.quantity,
      costPrice: request.costPrice,
      sellingPrice: request.sellingPrice,
      supplierId: request.supplierId,
      displayImageUrl: request.displayImageUrl, // Add image URL
      purchaseDetails: {
        'source': 'direct_sell_from_media',
        'created_at': DateTime.now().toIso8601String(),
        'auto_generated': true,
      },
    );

    return businessInventoryId;
  }

  /// Allocate inventory to specific store
  Future<void> _allocateToStoreInventory({
    required String businessId,
    required String businessName,
    required String vendorId,
    required String storeId,
    required String businessInventoryId,
    required String productId,
    required DirectSellRequest request,
  }) async {
    await _storeInventoryService.createStoreInventory(
      businessId: businessId,
      businessName: businessName,
      vendorId: vendorId,
      storeId: storeId,
      businessInventoryId: businessInventoryId,
      productId: productId,
      productName: request.productName,
      quantity: request.quantity,
      minimumQuantity: request.minimumQuantity ?? 5,
      unitPrice: request.sellingPrice,
      location: request.storeLocation,
      notes: 'Auto-allocated from direct sell',
      category: request.category ?? 'Uncategorized',
      displayImageUrl: request.displayImageUrl,
    );
  }

  /// Create sale order for the direct sell
  Future<order_model.Order> _createSaleOrder({
    required String productId,
    required String vendorId,
    required DirectSellRequest request,
  }) async {
    final orderItem = order_model.OrderItem(
      productId: productId,
      productName: request.productName,
      productImage: null, // Can be updated later with media URL
      price: request.sellingPrice,
      quantity: request.quantityToSell ?? 1,
      total: request.sellingPrice * (request.quantityToSell ?? 1),
    );

    final subtotal = orderItem.total;
    final tax = subtotal * (request.taxRate ?? 0.0);
    final shipping = request.shippingCost ?? 0.0;
    final total = subtotal + tax + shipping;

    final order = order_model.Order(
      id: '', // Will be generated
      vendorId: vendorId,
      customerId: request.customerId ?? 'walk-in-customer',
      customerName: request.customerName ?? 'Walk-in Customer',
      customerEmail: request.customerEmail ?? '',
      customerPhone: request.customerPhone ?? '',
      items: [orderItem],
      subtotal: subtotal,
      tax: tax,
      shipping: shipping,
      total: total,
      shippingAddress: request.shippingAddress ?? 'In-store pickup',
      paymentMethod: request.paymentMethod ?? 'cash',
      paymentStatus: 'paid', // Direct sell is typically paid immediately
      status: order_model.OrderStatus.delivered, // Direct sell is delivered immediately
      notes: 'Direct sell from media - Auto-generated order',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      deliveredAt: DateTime.now(), // Immediate delivery for direct sells
    );

    // Create order using OrderService
    final orderId = await _createOrderInFirestore(order, vendorId);
    return order.copyWith(id: orderId);
  }

  /// Helper to create order in Firestore
  Future<String> _createOrderInFirestore(order_model.Order order, String vendorId) async {
    final docRef = await _firestore.collection('orders').add(order.toMap());
    return docRef.id;
  }

  /// Quick sell with minimal details (one-tap sell)
  Future<DirectSellResult> quickSellFromMedia({
    required AssetEntity media,
    required String businessId,
    required String businessName,
    required String vendorId,
    required String storeId,
    required String storeName,
    required double price,
    String? customerName,
  }) async {
    final quickRequest = DirectSellRequest(
      productName: 'Quick Sell Item ${DateTime.now().millisecondsSinceEpoch}',
      sellingPrice: price,
      costPrice: price * 0.6, // Assume 40% margin
      quantity: 1,
      quantityToSell: 1,
      customerName: customerName ?? 'Walk-in Customer',
      paymentMethod: 'cash',
    );

    return await sellMediaDirectly(
      media: media,
      businessId: businessId,
      businessName: businessName,
      vendorId: vendorId,
      storeId: storeId,
      storeName: storeName,
      request: quickRequest,
    );
  }

  /// Add media item directly to store inventory without selling
  /// This creates the product and adds it to store inventory for future sales
  Future<DirectStoreAddResult> addMediaToStoreDirectly({
    required AssetEntity media,
    required String businessId,
    required String businessName,
    required String vendorId,
    required String storeId,
    required String storeName,
    required DirectStoreAddRequest request,
  }) async {
    try {
      // Step 1: Create product from media
      final product = await _createProductFromMedia(
        media: media,
        businessId: businessId,
        vendorId: vendorId,
        request: DirectSellRequest(
          productName: request.productName,
          productDescription: request.productDescription,
          sellingPrice: request.sellingPrice,
          costPrice: request.costPrice,
          quantity: request.quantity,
          quantityToSell: 0, // Not selling, just adding to inventory
          customerName: '',
          paymentMethod: '',
          category: request.category,
          tags: request.tags,
          unit: request.unit,
        ),
      );

      // Step 2: Add to business inventory (warehouse level)
      final businessInventoryId = await _addToBusinessInventory(
        productId: product.id,
        businessId: businessId,
        request: DirectSellRequest(
          productName: request.productName,
          productDescription: request.productDescription,
          sellingPrice: request.sellingPrice,
          costPrice: request.costPrice,
          quantity: request.quantity,
          quantityToSell: 0,
          customerName: '',
          paymentMethod: '',
          category: request.category,
          tags: request.tags,
          unit: request.unit,
        ),
      );

      // Step 3: Allocate to store inventory (available for sale)
      await _allocateToStoreInventory(
        businessId: businessId,
        businessName: businessName,
        vendorId: vendorId,
        storeId: storeId,
        businessInventoryId: businessInventoryId,
        productId: product.id,
        request: DirectSellRequest(
          productName: request.productName,
          productDescription: request.productDescription,
          sellingPrice: request.sellingPrice,
          costPrice: request.costPrice,
          quantity: request.quantity,
          quantityToSell: 0,
          customerName: '',
          paymentMethod: '',
          category: request.category,
          tags: request.tags,
          unit: request.unit,
        ),
      );

      return DirectStoreAddResult(
        success: true,
        productId: product.id,
        productName: product.name,
        businessInventoryId: businessInventoryId,
        storeId: storeId,
        quantityAdded: request.quantity,
        totalValue: request.sellingPrice * request.quantity,
      );

    } catch (e) {
      return DirectStoreAddResult(
        success: false,
        errorMessage: 'Failed to add media to store: $e',
      );
    }
  }

  /// Quick add to store with minimal details
  Future<DirectStoreAddResult> quickAddMediaToStore({
    required AssetEntity media,
    required String businessId,
    required String businessName,
    required String vendorId,
    required String storeId,
    required String storeName,
    required double price,
    int quantity = 1,
    String? category,
  }) async {
    final quickRequest = DirectStoreAddRequest(
      productName: 'Store Item ${DateTime.now().millisecondsSinceEpoch}',
      sellingPrice: price,
      costPrice: price * 0.6, // Assume 40% margin
      quantity: quantity,
      category: category ?? 'Uncategorized',
    );

    return await addMediaToStoreDirectly(
      media: media,
      businessId: businessId,
      businessName: businessName,
      vendorId: vendorId,
      storeId: storeId,
      storeName: storeName,
      request: quickRequest,
    );
  }
}

/// Request object for direct sell functionality
class DirectSellRequest {
  final String productName;
  final String? productDescription;
  final double sellingPrice;
  final double costPrice;
  final int quantity; // Total quantity to add to inventory
  final int? quantityToSell; // Quantity to sell (defaults to 1)
  final String? category;
  final List<String>? tags;
  final String? unit;
  final int? minimumQuantity;
  final String? storeLocation;
  final String? supplierId;
  final String? displayImageUrl; // Add product image URL

  // Customer and order details
  final String? customerId;
  final String? customerName;
  final String? customerEmail;
  final String? customerPhone;
  final String? shippingAddress;
  final String? paymentMethod;
  final double? taxRate;
  final double? shippingCost;

  DirectSellRequest({
    required this.productName,
    required this.sellingPrice,
    required this.costPrice,
    required this.quantity,
    this.productDescription,
    this.quantityToSell,
    this.category,
    this.tags,
    this.unit,
    this.minimumQuantity,
    this.storeLocation,
    this.supplierId,
    this.displayImageUrl, // Add to constructor
    this.customerId,
    this.customerName,
    this.customerEmail,
    this.customerPhone,
    this.shippingAddress,
    this.paymentMethod,
    this.taxRate,
    this.shippingCost,
  });
}

/// Result object for direct sell operation
class DirectSellResult {
  final bool success;
  final String? productId;
  final String? productName;
  final String? orderId;
  final String? businessInventoryId;
  final double? totalAmount;
  final String? errorMessage;

  DirectSellResult({
    required this.success,
    this.productId,
    this.productName,
    this.orderId,
    this.businessInventoryId,
    this.totalAmount,
    this.errorMessage,
  });

  @override
  String toString() {
    if (success) {
      return 'DirectSellResult: Success - Product: $productName (ID: $productId), Order: $orderId, Amount: \$$totalAmount';
    } else {
      return 'DirectSellResult: Failed - $errorMessage';
    }
  }
}

/// Extension for Product model to support copying with new ID
extension ProductExtension on Product {
  Product copyWith({
    String? id,
    String? name,
    String? description,
    double? price,
    List<String>? images,
    int? stock,
    int? minQuantity,
    double? rating,
    int? reviews,
    String? category,
    List<String>? tags,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? vendorId,
    String? businessId,
    String? unit,
    String? displayImageUrl,
  }) {
    return Product(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
      price: price ?? this.price,
      images: images ?? this.images,
      stock: stock ?? this.stock,
      minQuantity: minQuantity ?? this.minQuantity,
      rating: rating ?? this.rating,
      reviews: reviews ?? this.reviews,
      category: category ?? this.category,
      tags: tags ?? this.tags,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      vendorId: vendorId ?? this.vendorId,
      businessId: businessId ?? this.businessId,
      unit: unit ?? this.unit,
      displayImageUrl: displayImageUrl ?? this.displayImageUrl,
    );
  }
}

/// Extension for Order model to support copying with new ID
extension OrderExtension on order_model.Order {
  order_model.Order copyWith({
    String? id,
    String? vendorId,
    String? customerId,
    String? customerName,
    String? customerEmail,
    String? customerPhone,
    List<order_model.OrderItem>? items,
    double? subtotal,
    double? tax,
    double? shipping,
    double? total,
    String? shippingAddress,
    String? paymentMethod,
    String? paymentStatus,
    order_model.OrderStatus? status,
    String? trackingNumber,
    String? notes,
    DateTime? createdAt,
    DateTime? updatedAt,
    DateTime? deliveredAt,
    DateTime? cancelledAt,
  }) {
    return order_model.Order(
      id: id ?? this.id,
      vendorId: vendorId ?? this.vendorId,
      customerId: customerId ?? this.customerId,
      customerName: customerName ?? this.customerName,
      customerEmail: customerEmail ?? this.customerEmail,
      customerPhone: customerPhone ?? this.customerPhone,
      items: items ?? this.items,
      subtotal: subtotal ?? this.subtotal,
      tax: tax ?? this.tax,
      shipping: shipping ?? this.shipping,
      total: total ?? this.total,
      shippingAddress: shippingAddress ?? this.shippingAddress,
      paymentMethod: paymentMethod ?? this.paymentMethod,
      paymentStatus: paymentStatus ?? this.paymentStatus,
      status: status ?? this.status,
      trackingNumber: trackingNumber ?? this.trackingNumber,
      notes: notes ?? this.notes,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      deliveredAt: deliveredAt ?? this.deliveredAt,
      cancelledAt: cancelledAt ?? this.cancelledAt,
    );
  }
}

/// Request object for adding media directly to store inventory
class DirectStoreAddRequest {
  final String productName;
  final String? productDescription;
  final double sellingPrice;
  final double costPrice;
  final int quantity; // Quantity to add to store inventory
  final String? category;
  final List<String>? tags;
  final String? unit;

  DirectStoreAddRequest({
    required this.productName,
    this.productDescription,
    required this.sellingPrice,
    required this.costPrice,
    required this.quantity,
    this.category,
    this.tags,
    this.unit,
  });
}

/// Result object for direct store add functionality
class DirectStoreAddResult {
  final bool success;
  final String? productId;
  final String? productName;
  final String? businessInventoryId;
  final String? storeId;
  final int? quantityAdded;
  final double? totalValue;
  final String? errorMessage;

  DirectStoreAddResult({
    required this.success,
    this.productId,
    this.productName,
    this.businessInventoryId,
    this.storeId,
    this.quantityAdded,
    this.totalValue,
    this.errorMessage,
  });

  @override
  String toString() {
    if (success) {
      return 'DirectStoreAddResult: Success - Product: $productName (ID: $productId), Quantity Added: $quantityAdded, Total Value: \$$totalValue';
    } else {
      return 'DirectStoreAddResult: Failed - $errorMessage';
    }
  }
}
