import 'package:flutter/foundation.dart';
import 'package:google_mlkit_smart_reply/google_mlkit_smart_reply.dart' as ml;
import '../models/message.dart';

/// Service to generate AI-powered smart reply suggestions using Google ML Kit
///
/// This service uses Google ML Kit's on-device Smart Reply API to generate
/// contextual, intelligent reply suggestions based on conversation history.
///
/// **Benefits:**
/// - ✅ Free (no API costs)
/// - ✅ On-device ML (fast, private)
/// - ✅ Context-aware AI suggestions
/// - ✅ Works offline
/// - ✅ Supports multiple languages
///
/// **How it works:**
/// 1. Takes conversation history (last 10 messages)
/// 2. Feeds to ML Kit's SmartReply model
/// 3. Returns 3 AI-generated contextual suggestions
/// 4. Falls back to generic suggestions if ML fails
///
/// **Usage:**
/// ```dart
/// final service = SmartReplyService();
/// final suggestions = await service.getSuggestions(
///   messages: conversationMessages,
///   userId: currentUserId,
/// );
/// // Returns: ["Yes, I can help!", "Sure thing!", "Let me check that."]
/// ```
class SmartReplyService {
  final ml.SmartReply _smartReply = ml.SmartReply();

  /// Generate smart reply suggestions using ML Kit
  ///
  /// Analyzes conversation history with on-device ML to generate
  /// contextual, intelligent reply suggestions.
  ///
  /// **Parameters:**
  /// - [messages]: List of recent messages (last 10 recommended)
  /// - [userId]: Current user ID (to identify which side is user vs customer)
  ///
  /// **Returns:**
  /// List of 0-3 suggestion strings generated by ML Kit
  ///
  /// **Example:**
  /// ```dart
  /// final suggestions = await getSuggestions(
  ///   messages: recentMessages,
  ///   userId: 'vendor_123',
  /// );
  /// ```
  Future<List<String>> getSuggestions({
    required List<Message> messages,
    required String userId,
  }) async {
    try {
      if (messages.isEmpty) {
        debugPrint('⚠️ SmartReply: No messages for context');
        return [];
      }

      // Take last 10 messages for context (ML Kit works best with recent context)
      final recentMessages = messages.take(10).toList();

      // Clear previous conversation and add messages to ML Kit
      _addMessagesToConversation(recentMessages);

      debugPrint(
          '🤖 SmartReply: Analyzing ${recentMessages.length} messages...');

      // Get ML-powered suggestions (no arguments - uses added messages)
      final response = await _smartReply.suggestReplies();

      if (response.suggestions.isNotEmpty) {
        final suggestions = response.suggestions;
        debugPrint(
            '✅ SmartReply: Generated ${suggestions.length} AI suggestions');
        return suggestions;
      } else {
        debugPrint('ℹ️ SmartReply: ML returned no suggestions, using fallback');
        return _getGenericSuggestions();
      }
    } catch (e) {
      // Graceful failure - don't break chat UI
      debugPrint('❌ SmartReply error: $e');
      return _getGenericSuggestions();
    }
  }

  /// Add messages to ML Kit conversation
  ///
  /// ML Kit expects messages in chronological order (oldest first).
  /// Messages are added using the SmartReply API methods:
  /// - `addMessageToConversationFromLocalUser` for vendor messages
  /// - `addMessageToConversationFromRemoteUser` for customer messages
  void _addMessagesToConversation(List<Message> messages) {
    // Messages come in reverse chronological (newest first), so reverse them
    final chronological = messages.reversed.toList();

    for (final msg in chronological) {
      final text = msg.content.text?.trim() ?? '';

      // Skip empty messages
      if (text.isEmpty) continue;

      final timestamp = msg.createdAt.millisecondsSinceEpoch;

      // Determine if message is from local user (vendor) or remote (customer)
      if (msg.sender.isCustomer) {
        // Customer message (remote user)
        _smartReply.addMessageToConversationFromRemoteUser(
          text,
          timestamp,
          msg.sender.id,
        );
      } else {
        // Vendor message (local user)
        _smartReply.addMessageToConversationFromLocalUser(
          text,
          timestamp,
        );
      }
    }
  }

  /// Fallback suggestions when ML Kit fails or returns nothing
  List<String> _getGenericSuggestions() {
    return [
      "Thank you for your message!",
      "Let me check that for you.",
      "How can I assist you further?",
    ];
  }

  /// Clean up ML Kit resources
  void dispose() {
    _smartReply.close();
  }
}
