// Mocks generated by Mockito 5.4.4 from annotations
// in vendor_app/test/services/product_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:vendor_app/services/firestore_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCollectionReference_0<T extends Object?> extends _i1.SmartFake
    implements _i2.CollectionReference<T> {
  _FakeCollectionReference_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentSnapshot_1<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentSnapshot<T> {
  _FakeDocumentSnapshot_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuerySnapshot_2<T extends Object?> extends _i1.SmartFake
    implements _i2.QuerySnapshot<T> {
  _FakeQuerySnapshot_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentReference_3<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T> {
  _FakeDocumentReference_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSnapshotMetadata_4 extends _i1.SmartFake
    implements _i2.SnapshotMetadata {
  _FakeSnapshotMetadata_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i3.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CollectionReference<Object?> get usersCollection => (super.noSuchMethod(
        Invocation.getter(#usersCollection),
        returnValue: _FakeCollectionReference_0<Object?>(
          this,
          Invocation.getter(#usersCollection),
        ),
      ) as _i2.CollectionReference<Object?>);

  @override
  _i2.CollectionReference<Object?> get productsCollection =>
      (super.noSuchMethod(
        Invocation.getter(#productsCollection),
        returnValue: _FakeCollectionReference_0<Object?>(
          this,
          Invocation.getter(#productsCollection),
        ),
      ) as _i2.CollectionReference<Object?>);

  @override
  _i2.CollectionReference<Object?> get mediaCollection => (super.noSuchMethod(
        Invocation.getter(#mediaCollection),
        returnValue: _FakeCollectionReference_0<Object?>(
          this,
          Invocation.getter(#mediaCollection),
        ),
      ) as _i2.CollectionReference<Object?>);

  @override
  _i4.Future<_i2.DocumentSnapshot<Object?>> getDocument(
    String? collection,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocument,
          [
            collection,
            id,
          ],
        ),
        returnValue: _i4.Future<_i2.DocumentSnapshot<Object?>>.value(
            _FakeDocumentSnapshot_1<Object?>(
          this,
          Invocation.method(
            #getDocument,
            [
              collection,
              id,
            ],
          ),
        )),
      ) as _i4.Future<_i2.DocumentSnapshot<Object?>>);

  @override
  _i4.Future<_i2.QuerySnapshot<Object?>> getCollection(
    String? collection, {
    _i2.Query<Object?> Function(_i2.Query<Object?>)? queryBuilder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCollection,
          [collection],
          {#queryBuilder: queryBuilder},
        ),
        returnValue: _i4.Future<_i2.QuerySnapshot<Object?>>.value(
            _FakeQuerySnapshot_2<Object?>(
          this,
          Invocation.method(
            #getCollection,
            [collection],
            {#queryBuilder: queryBuilder},
          ),
        )),
      ) as _i4.Future<_i2.QuerySnapshot<Object?>>);

  @override
  _i4.Future<_i2.DocumentReference<Object?>> addDocument(
    String? collection,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDocument,
          [
            collection,
            data,
          ],
        ),
        returnValue: _i4.Future<_i2.DocumentReference<Object?>>.value(
            _FakeDocumentReference_3<Object?>(
          this,
          Invocation.method(
            #addDocument,
            [
              collection,
              data,
            ],
          ),
        )),
      ) as _i4.Future<_i2.DocumentReference<Object?>>);

  @override
  _i4.Future<void> updateDocument(
    String? collection,
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocument,
          [
            collection,
            id,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteDocument(
    String? collection,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [
            collection,
            id,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> batchWrite(List<_i3.BatchOperation>? operations) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchWrite,
          [operations],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<_i2.QuerySnapshot<Object?>> streamCollection(
    String? collection, {
    _i2.Query<Object?> Function(_i2.Query<Object?>)? queryBuilder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamCollection,
          [collection],
          {#queryBuilder: queryBuilder},
        ),
        returnValue: _i4.Stream<_i2.QuerySnapshot<Object?>>.empty(),
      ) as _i4.Stream<_i2.QuerySnapshot<Object?>>);

  @override
  _i4.Stream<_i2.DocumentSnapshot<Object?>> streamDocument(
    String? collection,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamDocument,
          [
            collection,
            id,
          ],
        ),
        returnValue: _i4.Stream<_i2.DocumentSnapshot<Object?>>.empty(),
      ) as _i4.Stream<_i2.DocumentSnapshot<Object?>>);
}

/// A class which mocks [DocumentSnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentSnapshot<T extends Object?> extends _i1.Mock
    implements _i2.DocumentSnapshot<T> {
  MockDocumentSnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  _i2.DocumentReference<T> get reference => (super.noSuchMethod(
        Invocation.getter(#reference),
        returnValue: _FakeDocumentReference_3<T>(
          this,
          Invocation.getter(#reference),
        ),
      ) as _i2.DocumentReference<T>);

  @override
  _i2.SnapshotMetadata get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: _FakeSnapshotMetadata_4(
          this,
          Invocation.getter(#metadata),
        ),
      ) as _i2.SnapshotMetadata);

  @override
  bool get exists => (super.noSuchMethod(
        Invocation.getter(#exists),
        returnValue: false,
      ) as bool);

  @override
  dynamic get(Object? field) => super.noSuchMethod(Invocation.method(
        #get,
        [field],
      ));

  @override
  dynamic operator [](Object? field) => super.noSuchMethod(Invocation.method(
        #[],
        [field],
      ));
}

/// A class which mocks [QuerySnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuerySnapshot<T extends Object?> extends _i1.Mock
    implements _i2.QuerySnapshot<T> {
  MockQuerySnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.QueryDocumentSnapshot<T>> get docs => (super.noSuchMethod(
        Invocation.getter(#docs),
        returnValue: <_i2.QueryDocumentSnapshot<T>>[],
      ) as List<_i2.QueryDocumentSnapshot<T>>);

  @override
  List<_i2.DocumentChange<T>> get docChanges => (super.noSuchMethod(
        Invocation.getter(#docChanges),
        returnValue: <_i2.DocumentChange<T>>[],
      ) as List<_i2.DocumentChange<T>>);

  @override
  _i2.SnapshotMetadata get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: _FakeSnapshotMetadata_4(
          this,
          Invocation.getter(#metadata),
        ),
      ) as _i2.SnapshotMetadata);

  @override
  int get size => (super.noSuchMethod(
        Invocation.getter(#size),
        returnValue: 0,
      ) as int);
}
