// Mocks generated by Mockito 5.4.4 from annotations
// in vendor_app/test/screens/product_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vendor_app/models/product.dart' as _i4;
import 'package:vendor_app/models/product_listing.dart' as _i2;
import 'package:vendor_app/services/product_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductAnalytics_0 extends _i1.SmartFake
    implements _i2.ProductAnalytics {
  _FakeProductAnalytics_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductService extends _i1.Mock implements _i3.ProductService {
  MockProductService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.Product> get products => (super.noSuchMethod(
        Invocation.getter(#products),
        returnValue: <_i4.Product>[],
      ) as List<_i4.Product>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> fetchProducts() => (super.noSuchMethod(
        Invocation.method(
          #fetchProducts,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i4.Product?> getProduct(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getProduct,
          [id],
        ),
        returnValue: _i5.Future<_i4.Product?>.value(),
      ) as _i5.Future<_i4.Product?>);

  @override
  _i5.Future<bool> createProduct(_i4.Product? product) => (super.noSuchMethod(
        Invocation.method(
          #createProduct,
          [product],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateProduct(_i4.Product? product) => (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [product],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteProduct(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<_i4.Product>> searchProducts(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProducts,
          [query],
        ),
        returnValue: _i5.Future<List<_i4.Product>>.value(<_i4.Product>[]),
      ) as _i5.Future<List<_i4.Product>>);

  @override
  _i5.Future<List<_i4.Product>> getProductsByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByCategory,
          [category],
        ),
        returnValue: _i5.Future<List<_i4.Product>>.value(<_i4.Product>[]),
      ) as _i5.Future<List<_i4.Product>>);

  @override
  _i5.Stream<List<_i4.Product>> streamProducts() => (super.noSuchMethod(
        Invocation.method(
          #streamProducts,
          [],
        ),
        returnValue: _i5.Stream<List<_i4.Product>>.empty(),
      ) as _i5.Stream<List<_i4.Product>>);

  @override
  _i5.Stream<_i4.Product?> streamProduct(String? id) => (super.noSuchMethod(
        Invocation.method(
          #streamProduct,
          [id],
        ),
        returnValue: _i5.Stream<_i4.Product?>.empty(),
      ) as _i5.Stream<_i4.Product?>);

  @override
  _i5.Future<List<_i2.ExternalListing>> getExternalListings(
          String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExternalListings,
          [productId],
        ),
        returnValue: _i5.Future<List<_i2.ExternalListing>>.value(
            <_i2.ExternalListing>[]),
      ) as _i5.Future<List<_i2.ExternalListing>>);

  @override
  _i5.Future<void> updateExternalListing({
    required String? productId,
    required String? listingId,
    required Map<String, dynamic>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExternalListing,
          [],
          {
            #productId: productId,
            #listingId: listingId,
            #updates: updates,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeExternalListing({
    required String? productId,
    required String? listingId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeExternalListing,
          [],
          {
            #productId: productId,
            #listingId: listingId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.ProductAnalytics> getProductAnalytics(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductAnalytics,
          [productId],
        ),
        returnValue:
            _i5.Future<_i2.ProductAnalytics>.value(_FakeProductAnalytics_0(
          this,
          Invocation.method(
            #getProductAnalytics,
            [productId],
          ),
        )),
      ) as _i5.Future<_i2.ProductAnalytics>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getTopReviews(
    String? productId, {
    int? limit = 2,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopReviews,
          [productId],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getTopComplaints(
    String? productId, {
    int? limit = 2,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopComplaints,
          [productId],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getProductTasks(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductTasks,
          [productId],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
