// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV6EJ7TxGgx5FKBVbGhAFYoyK66aNPSqU',
    appId: '1:229268356345:web:ab7b958690708cc309f628',
    messagingSenderId: '229268356345',
    projectId: 'sme-afrika',
    authDomain: 'sme-afrika.firebaseapp.com',
    storageBucket: 'sme-afrika.firebasestorage.app',
    measurementId: 'G-8F0HJJDWMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLdlndZC5sRog6d2dGSfjdoUZwSjxslq0',
    appId: '1:229268356345:android:5fb7d1803cca126609f628',
    messagingSenderId: '229268356345',
    projectId: 'sme-afrika',
    storageBucket: 'sme-afrika.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKY9Xjwg7cjeVh4t831erk0RTQLeUcUDg',
    appId: '1:229268356345:ios:6254b58aa6d1026309f628',
    messagingSenderId: '229268356345',
    projectId: 'sme-afrika',
    storageBucket: 'sme-afrika.firebasestorage.app',
    iosBundleId: 'com.example.vendorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKY9Xjwg7cjeVh4t831erk0RTQLeUcUDg',
    appId: '1:229268356345:ios:6254b58aa6d1026309f628',
    messagingSenderId: '229268356345',
    projectId: 'sme-afrika',
    storageBucket: 'sme-afrika.firebasestorage.app',
    iosBundleId: 'com.example.vendorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV6EJ7TxGgx5FKBVbGhAFYoyK66aNPSqU',
    appId: '1:229268356345:web:ea2d505dd10988e209f628',
    messagingSenderId: '229268356345',
    projectId: 'sme-afrika',
    authDomain: 'sme-afrika.firebaseapp.com',
    storageBucket: 'sme-afrika.firebasestorage.app',
    measurementId: 'G-YDCFTBWTZP',
  );
}
