import { Injectable, BadRequestException, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import * as path from 'path';
import * as fs from 'fs/promises';
import { ContentModerationService, ModerationResult } from '../content-moderation.service';

// Video metadata interfaces
export interface VideoMetadata {
  duration: number; // seconds (provided by frontend)
  width: number; // pixels (provided by frontend)
  height: number; // pixels (provided by frontend)
  size: number; // bytes
  format: string; // mp4, mov, avi
}

export interface ProcessedVideo {
  videoPath: string;
  thumbnailPath: string;
  metadata: VideoMetadata;
  moderationResult: ModerationResult;
}

@Injectable()
export class VideoProcessorService {
  private readonly logger = new Logger(VideoProcessorService.name);
  private readonly maxDuration = 10; // 10 seconds
  private readonly maxFileSize = 50 * 1024 * 1024; // 50MB

  constructor(
    private readonly configService: ConfigService,
    private readonly contentModeration: ContentModerationService,
  ) {}

  /**
   * Process video: validate, moderate thumbnail (thumbnail generated by frontend)
   * 
   * @param videoPath - Path to video file
   * @param thumbnailPath - Path to thumbnail file (generated by frontend)
   * @param frontendMetadata - Metadata from frontend (duration, dimensions)
   */
  async processVideo(
    videoPath: string,
    thumbnailPath: string,
    frontendMetadata: { duration: number; width: number; height: number },
  ): Promise<ProcessedVideo> {
    try {
      this.logger.log(`Processing video: ${videoPath}`);
      this.logger.log(`Using frontend-generated thumbnail: ${thumbnailPath}`);

      // Step 1: Validate files exist
      await this.validateFileExists(videoPath);
      await this.validateFileExists(thumbnailPath);

      // Step 2: Get file size and format
      const stats = await fs.stat(videoPath);
      const size = stats.size;
      const format = path.extname(videoPath).substring(1).toLowerCase();

      // Step 3: Validate duration (from frontend metadata)
      if (frontendMetadata.duration > this.maxDuration) {
        throw new BadRequestException(
          `Video duration exceeds ${this.maxDuration} seconds. Duration: ${frontendMetadata.duration.toFixed(1)}s`,
        );
      }

      // Step 4: Validate file size
      if (size > this.maxFileSize) {
        throw new BadRequestException(
          `Video file size exceeds ${this.maxFileSize / (1024 * 1024)}MB. Size: ${(size / (1024 * 1024)).toFixed(2)}MB`,
        );
      }

      // Step 5: Create metadata
      const metadata: VideoMetadata = {
        duration: frontendMetadata.duration,
        width: frontendMetadata.width,
        height: frontendMetadata.height,
        size,
        format,
      };

      this.logger.log(`Video metadata: ${JSON.stringify(metadata)}`);

      // Step 6: Moderate thumbnail using Google Vision API
      const moderationResult =
        await this.contentModeration.moderateImage(thumbnailPath);
      this.logger.log(
        `Moderation result: ${JSON.stringify(moderationResult)}`,
      );

      if (!moderationResult.isSafe) {
        // Clean up files
        await this.cleanupFiles([videoPath, thumbnailPath]);
        throw new BadRequestException(
          'Video thumbnail contains inappropriate content. Upload rejected.',
        );
      }

      return {
        videoPath,
        thumbnailPath,
        metadata,
        moderationResult,
      };
    } catch (error) {
      this.logger.error(`Video processing failed: ${error.message}`, error.stack);
      throw error;
    }
  }

  /**
   * Validate file exists
   */
  private async validateFileExists(filePath: string): Promise<void> {
    try {
      await fs.access(filePath);
    } catch (error) {
      throw new BadRequestException(`File not found: ${filePath}`);
    }
  }

  /**
   * Clean up temporary files
   */
  async cleanupFiles(filePaths: string[]): Promise<void> {
    for (const filePath of filePaths) {
      try {
        await fs.unlink(filePath);
        this.logger.log(`Cleaned up file: ${filePath}`);
      } catch (error) {
        this.logger.warn(`Failed to cleanup file ${filePath}: ${error.message}`);
      }
    }
  }

  /**
   * Validate video file type by checking magic bytes
   */
  async validateVideoFile(buffer: Buffer): Promise<void> {
    const magicBytes = buffer.slice(0, 12);

    // MP4: starts with ftyp
    const isMp4 =
      magicBytes.slice(4, 8).toString('ascii') === 'ftyp' ||
      magicBytes.slice(4, 11).toString('ascii') === 'ftypiso' ||
      magicBytes.slice(4, 12).toString('ascii') === 'ftypisom';

    // MOV/QuickTime: starts with moov or ftyp
    const isMov =
      magicBytes.slice(4, 8).toString('ascii') === 'moov' ||
      magicBytes.slice(4, 12).toString('ascii') === 'ftypqt  ';

    // AVI: starts with RIFF....AVI
    const isAvi =
      magicBytes.slice(0, 4).toString('ascii') === 'RIFF' &&
      magicBytes.slice(8, 11).toString('ascii') === 'AVI';

    if (!isMp4 && !isMov && !isAvi) {
      throw new BadRequestException(
        'Invalid video file type. Only MP4, MOV, and AVI are supported.',
      );
    }
  }

  /**
   * Validate thumbnail file type by checking magic bytes
   */
  async validateThumbnailFile(buffer: Buffer): Promise<void> {
    const magicBytes = buffer.slice(0, 8);

    // JPEG: FF D8 FF
    const isJpeg = magicBytes[0] === 0xff && magicBytes[1] === 0xd8 && magicBytes[2] === 0xff;

    // PNG: 89 50 4E 47
    const isPng =
      magicBytes[0] === 0x89 &&
      magicBytes[1] === 0x50 &&
      magicBytes[2] === 0x4e &&
      magicBytes[3] === 0x47;

    if (!isJpeg && !isPng) {
      throw new BadRequestException(
        'Invalid thumbnail file type. Only JPEG and PNG are supported.',
      );
    }
  }
}
